default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: 4130
  host: localhost
  database: protospace_39415_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password: 4130
  host: localhost
  database: protospace_39415_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>